### ISSUE TITLE
About the bias settings

### ISSUE THREAD

**Issue by AGI-player** [chaytonmin/Occupancy-MAE#23]
Thanks for your great work.
The bias settings in spconv_backone.py line 39: bias = bias, while in voxel_mae_res.py line 18: bias =False, this may cause faileures in loading pretrained_models, why?

**Comment by chaytonmin** [comment]
> Thanks for your great work. The bias settings in spconv_backone.py line 39: bias = bias, while in voxel_mae_res.py line 18: bias =False, this may cause faileures in loading pretrained_models, why?

Thank you for pointing out this problem.
