### ISSUE TITLE
Inconsistent setting between the configs in repo and paper

### ISSUE THREAD

**Issue by FrontierBreaker** [chaytonmin/Occupancy-MAE#24]
Hi, I find that the pretrain epoches for the paper is set as 3 eps as default while it is set as 20 in this repo. Which is right?

**Comment by chaytonmin** [comment]
> Hi, I find that the pretrain epoches for the paper is set as 3 eps as default while it is set as 20 in this repo. Which is right?

We just use the models of 3 epochs.  You can also try another one

**Comment by FrontierBreaker** [comment]
so you mean use the pretraining epoches (e.g., 20 for nuscenes) in the current cfg files

and use the model ckpt pf 3 epoch for downstream evaluation? @chaytonmin

**Comment by chaytonmin** [comment]
> so you mean use the pretraining epoches (e.g., 20 for nuscenes) in the current cfg files
> 
> and use the model ckpt pf 3 epoch for downstream evaluation? @chaytonmin

yes

**Comment by FrontierBreaker** [comment]
get thanks!!
