### ISSUE TITLE
Masking Implementation

### ISSUE THREAD

**Issue by YilmazKadir** [chaytonmin/Occupancy-MAE#4]
In the paper, you say that you mask the point cloud similar to MAE but I could not find the details. In MAE image is divided into patches that contain 14x14 pixels and then randomly masked at patch level. Do you also divide the scenes into 14x14x14 voxels similarly, or do you just randomly select 50% of voxels in each scene and mask them?

**Comment by chaytonmin** [comment]
> just randomly select 50% of voxels in each scene and mask them

We just randomly select 50% of voxels in each scene and mask them. The pathes in MAE are similar to the voxels in our Voxel-MAE.

**Comment by alpacaduby** [comment]
The paper indicates that mask ratio varies with distance, but I can't find the related code.Can you please tell me where it is,or you just set the mask ratio to 50% in spite of distance?

**Comment by chaytonmin** [comment]
> The paper indicates that mask ratio varies with distance, but I can't find the related code.Can you please tell me where it is,or you just set the mask ratio to 50% in spite of distance?

Please refer to:

https://github.com/chaytonmin/Voxel-MAE/blob/459fafc67300a63a345edeb4701cd2adf24e4838/tools/cfgs/kitti_models/voxel_mae_kitti.yaml#L15

https://github.com/chaytonmin/Voxel-MAE/blob/459fafc67300a63a345edeb4701cd2adf24e4838/pcdet/models/backbones_3d/voxel_mae.py#L157

**Comment by YilmazKadir** [comment]
But then you mask 50% (0-30) and 30% for (30-inf). In the paper, you claim "For voxels within 0-30 meters, 30-50 meters, and > 50 meters, we set the masking ratio to 90%, 70%, and 50%, respectively."

**Comment by chaytonmin** [comment]
> Voxel-MAE/tools/cfgs/kitti_models/voxel_mae_kitti.yaml

You can set the masking ratio to 90% in 
https://github.com/chaytonmin/Voxel-MAE/blob/459fafc67300a63a345edeb4701cd2adf24e4838/tools/cfgs/kitti_models/voxel_mae_kitti.yaml#L15
